name: CI/CD

on:
  push: 
    branches: [ main ]
    paths: 
    - 'main.py' 
    - 'apply_pylint.py'
    - 'tests/'

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v2
    - name: Set up Python 3.8 
      uses: actions/setup-python@v2 
      with: 
        python-version: 3.8 

    - name: Install dependencies 
      run: |
        python -m pip install --upgrade pip 
        pip install pylint

    - name: Lint with pylint
      run: | 
        echo "Checking Pylint!"
        python apply_pylint.py

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install dependencies
        run: |
          pip install pytest
          pip install pytest-cov
          pip install coverage

      - name: Run tests
        run: |
          echo "Testing the Python Code!"
          pytest -v ./tests
          coverage run --source=. -m pytest
          coverage report -m
