name: CI/CD

on:
  push: 
    branches: [ main ]
    paths: 
    - 'main.py' 
    - 'apply_pylint.py'
    - 'test_main.py'
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v2 

    - name: Set up Python 3.8 
      uses: actions/setup-python@v2 
      with: 
        python-version: 3.8 

    - name: Install dependencies 
      run: |
        python -m pip install --upgrade pip 
        pip install pylint
        pip install pytest
        pip install pytest-cov
        pip install coverage

    - name: Lint with pylint
      run: | 
        echo "Check Pylint!"
        python apply_pylint.py

  test:
    runs-on: ubuntu-latest

    needs: build
    steps:
      - name: Run tests
        run: |
          echo "Testing the Python Code!"
          python test_main.py
          coverage run --source=. -m pytest
          coverage report -m
